version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: investment
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  flask-api:
    build:
      context: ./api
    container_name: flask_api
    environment:
      - DATABASE_URI=mysql+pymysql://root:password@db/investment
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: >
      sh -c "
      python create_db.py &&
      python app.py
      "

  angular-app:
    build:
      context: ./app
    container_name: angular_app
    ports:
      - "80:80"
    depends_on:
      - flask-api

volumes:
  db_data:
